---
jobs:
- name: hello-world
  plan:
  - task: hello-world
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: busybox }
      run:
        path: env
        args: []
    params:
      USERNAME: ((foo_param))
